.tests: &tests
  tags:
    - docker
  before_script:
    - pip install tox

pycodestyle:
  <<: *tests
  image: python
  script:
    - pip install pycodestyle
    - pycodestyle atlassian2gitlab/ tests/

python35:
  <<: *tests
  image: python:3.5
  script: tox -e py35

python36:
  <<: *tests
  image: python:3.6
  script: tox -e py36

pypy3:
  <<: *tests
  image: pypy:3
  script: tox -e pypy3
